# WELCOME TO NUMPY

### Numpy nima

NumPy (Numerical Python) — bu Python dasturlash tilida hisob-kitoblarni amalga oshirish uchun moʻljallangan kuchli va keng tarqalgan kutubxona. NumPy asosan raqamli hisoblash uchun optimallashtirilgan, bu esa maʼlumotlar tahlili va ilmiy hisoblash jarayonlarida keng qoʻllanilishiga imkon beradi. Quyida NumPy ning asosiy jihatlari keltirilgan:

Asosiy Xususiyatlari:
Tez va samarali: NumPy, C va Fortran kabi past darajadagi tillarda yozilgan bo‘lib, katta o‘lchovdagi massivlarni (array) tezda hisoblash imkonini beradi.

N-dimensional massivlar: NumPy, 1D, 2D va n-dimensional massivlarni yaratish va ulardan foydalanish imkonini beradi. Massivlar Python ro‘yxatlaridan ko‘ra tezroq va samaraliroq.

Matematik va statistik funksiyalar: NumPy turli xil matematik va statistik funksiyalarni taqdim etadi, masalan, summalar, o‘rtacha, standart og‘ish, va boshqalar.

Broadcasting: NumPy dasturlashda avtomatik tarzda massivlar o‘rtasidagi har xil o‘lchovlarni boshqarishga imkon beruvchi broadcasting qoidalariga ega.

Ma'lumotlarni joylashtirish: NumPy ma'lumotlarni joylashtirish va saqlashni osonlashtiradi, shuningdek, matnli va binar fayllardan ma'lumotlarni o‘qish va yozish imkoniyatini beradi.

### Numpy ni o'rnatish
- pip
- conda

In [1]:
# conda install numpy

In [2]:
# pip install numpy

### Numpyni import qilish
- import numpy as np

In [3]:
import numpy as np

### numpy versiyasini ko'rish
- np.__version__

In [4]:
print(np.__version__)

1.26.1


### Massivlarni xosil qilish va o'lchamlarini ko'rish
- np.array()

In [5]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [6]:
print(type(list1))

<class 'list'>


In [7]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [8]:
print(type(arr1))

<class 'numpy.ndarray'>


In [9]:
arr1 = np.array(list1)
print(f'bu massiv {arr1}')
print(f'bu list {list1}')

bu massiv [1 2 3 4 5]
bu list [1, 2, 3, 4, 5]


In [10]:
# bir o'lchamli massiv
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [11]:
arr1.shape

(5,)

In [12]:
# ikki o'lchamli massiv
arr2 = np.array([[9,2,3], [4,5,6]])
print(arr2)

[[9 2 3]
 [4 5 6]]


In [13]:
arr2.shape

(2, 3)

In [14]:
# uch o'lchamli massiv
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[7,8,9], [10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
arr3.shape

(3, 2, 3)

### Massivlarni xosil qiluvchi funksiyalar
- zeros
- ones
- eye
- linspace
- fill

In [49]:
nollar = np.zeros(5)
print(nollar)
print(nollar.shape)

[0. 0. 0. 0. 0.]
(5,)


In [17]:
nollar = np.zeros((5, 6), dtype=int)
print(nollar)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [18]:
nollar = np.zeros((5, 6))
print(nollar.shape)
print(nollar)

(5, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
nollar = np.zeros((3,2,3), dtype=int)
print(nollar.shape)
print(nollar)

(3, 2, 3)
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [20]:
nollar = np.zeros((2,3,2,3))
print(nollar.shape)
print(nollar)

(2, 3, 2, 3)
[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]]


In [21]:
birlar = np.ones((2, 3))
print(birlar.shape)
print(birlar)

(2, 3)
[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
birlar = np.ones((2,4, 3))
print(birlar.shape)
print(birlar)

(2, 4, 3)
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [50]:
dioganal = np.eye(5)
print(dioganal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [52]:
chiziq = np.linspace(0,5,10)
chiziq

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [53]:
chiziq = np.linspace(-10,10,10)
chiziq

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

### Array (massiv) xaqida ma'lumotlar olish
- ndim
- shape
- dtype
- size

In [26]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [27]:
a = np.array(42)
b = np.array([1, 3,2,  4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(2, 2, 3)


In [144]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]], dtype=float)

print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int32
int32
int32
float64


In [145]:
a = np.array(42)
b = np.array([1, 3,2,  4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.size)
print(b.size)
print(c.size)
print(d.size)

1
5
6
12


### Numpy da random moduli
- rand
- randn
- randint
- shaflle
- normal
- uniform
- permutation
- arrange

In [78]:
# Generates a single random float in the range [0.0, 1.0)
random_float = np.random.rand()
print("Random Float:", random_float)

Random Float: 0.5677003278199915


In [146]:
# Generates a single random float in the range [0.0, 1.0)
random_float = np.random.rand(2, 3)
print(random_float.dtype)
print(random_float.shape)
print(random_float.ndim)
print("Random Float:", random_float)

float64
(2, 3)
2
Random Float: [[0.14660482 0.51332617 0.23322807]
 [0.58130542 0.86313852 0.88035997]]


In [98]:
# Generates a 1D array of 5 random floats in the range [0.0, 1.0)
random_floats_array = np.random.rand(5)
print("Random Floats Array:", random_floats_array)

Random Floats Array: [0.86040462 0.25025136 0.03883473 0.30326551 0.53708243]


In [119]:
# Generates a random integer between 10 and 50 (exclusive)
random_int = np.random.randint(10, 50)
print("Random Integer:", random_int)

Random Integer: 35


In [143]:
# Generates a 2x3 array of random integers between 10 and 50 (exclusive)
random_int_array = np.random.randint(0, 10, size=(2, 3, 3))
print("Random Integers Array:\n", random_int_array)

Random Integers Array:
 [[[9 6 9]
  [4 2 6]
  [1 8 9]]

 [[9 0 5]
  [6 7 9]
  [8 1 9]]]


In [150]:
# Generates a 1D array of 5 random floats with mean=10 and std=2
custom_normal_array = np.random.normal(10, 2, 5)
print("Custom Normal Distribution Array:", custom_normal_array)

Custom Normal Distribution Array: [11.53667891 11.10938559 11.46634673  7.79155642 11.52314368]


In [151]:
# Generates a 1D array of 5 random floats with mean=10 and std=2
custom_normal_array = np.random.normal(5, 3, 9)
print("Custom Normal Distribution Array:", custom_normal_array)

Custom Normal Distribution Array: [ 3.35222546 -2.37758009  5.17223884  2.4676768   9.0764499   4.14096045
  5.13682352  6.16753873  4.19779809]


In [156]:
# Generates a 2x3 array of random floats from a standard normal distribution
normal_random_array = np.random.randn(2, 3)
print("Normal Distribution Array:\n", normal_random_array)

Normal Distribution Array:
 [[-1.73031531  0.14205009  1.03715846]
 [-0.3097431  -1.16981703 -0.10798496]]


In [157]:
# Generates a 2x3 array of random floats in the range [5, 10)
uniform_array = np.random.uniform(5, 10, size=(2, 3), )
print("Uniform Distribution Array:\n", uniform_array)

Uniform Distribution Array:
 [[9.92643025 6.88369485 8.7478915 ]
 [6.96494724 9.1458211  7.84540735]]


In [159]:

uniform_array = np.random.uniform(0, 10, size=(3,2, 3), )
print("Uniform Distribution Array:\n", uniform_array)

Uniform Distribution Array:
 [[[5.34346275 7.49910749 9.13165752]
  [5.85149532 7.26120844 7.57081202]]

 [[3.77850549 2.41084832 2.05045329]
  [2.5144244  2.74731797 2.07227649]]

 [[8.78220667 7.56999132 0.46896468]
  [2.68672482 0.22184742 4.98165187]]]


In [184]:
# Selects a random element from a given array
choices = [10, 20, 30, 40, 50]
random_choice = np.random.choice(choices)
print("Random Choice:", random_choice)

Random Choice: 10


In [198]:
# Selects 3 random elements from the array (without replacement)
random_choices = np.random.choice(choices, size=3, replace=False)
print("Random Choices (No Replacement):", random_choices)

Random Choices (No Replacement): [40 30 10]


In [206]:
# Selects 3 random elements from the array (without replacement)
random_int = np.random.randint(0, 10, size=(7))
print("Random Integer:", random_int)
random_choices = np.random.choice(random_int, size=(3,6))
print("Random Choices (No Replacement):", random_choices)

Random Integer: [7 8 5 6 0 4 4]
Random Choices (No Replacement): [[8 4 6 4 4 7]
 [7 4 4 4 5 4]
 [0 4 7 0 7 8]]


In [197]:
array_to_shuffle = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array_to_shuffle)
print("Shuffled Array:", array_to_shuffle)

Shuffled Array: [3 5 1 2 4]


In [218]:
# Returns a new array with elements in random order
original_array = np.array([1, 2, 3, 4, 5])
permuted_array = np.random.permutation(original_array)
print("Original Array:", original_array)
print("Permuted Array:", permuted_array)

Original Array: [1 2 3 4 5]
Permuted Array: [1 3 5 2 4]


In [219]:
# Returns a new array with elements in random order
original_array = np.array([1, 2, 3, 4, 5])
permuted_array = np.random.permutation(original_array)
print("Original Array:", original_array)
print("Permuted Array:", permuted_array)

Original Array: [1 2 3 4 5]
Permuted Array: [2 3 1 4 5]


In [269]:
np.random.seed(42)
print("Random Integer with Seed:", np.random.randint(1, 100))
# Resetting the seed gives the same output
np.random.seed(42)
print("Random Integer with Same Seed:", np.random.randint(1, 100))

Random Integer with Seed: 52
Random Integer with Same Seed: 52


In [274]:
import numpy as np
ketmaket = np.arange(5,15, 2)
print(ketmaket)

[ 5  7  9 11 13]


In [44]:
tasodif = np.random.rand(2,2,3)

print(f'''o'lchami {tasodif.ndim}''')
print(f'''o'lchami {tasodif.shape}''')
print(tasodif)

o'lchami 3
o'lchami (2, 2, 3)
[[[0.95071431 0.73199394 0.59865848]
  [0.15601864 0.15599452 0.05808361]]

 [[0.86617615 0.60111501 0.70807258]
  [0.02058449 0.96990985 0.83244264]]]


In [45]:
tasodif1 = np.random.randn(2,3,2)

print(f'''o'lchami {tasodif1.ndim}''')
print(f'''o'lchami {tasodif1.shape}''')
print(tasodif1)

o'lchami 3
o'lchami (2, 3, 2)
[[[-0.58087813 -0.52516981]
  [-0.57138017 -0.92408284]
  [-2.61254901  0.95036968]]

 [[ 0.81644508 -1.523876  ]
  [-0.42804606 -0.74240684]
  [-0.7033438  -2.13962066]]]


In [46]:
tasodif2 = np.random.randint((1,10))

print(f'''o'lchami {tasodif2.ndim}''')
print(f'''o'lchami {tasodif2.shape}''')
print(tasodif2)

o'lchami 1
o'lchami (2,)
[0 2]


### Numpy da ma'lumot turlari

##### Python dasturlash tilida quyidagi ma'lumot turlarini bilamiz
- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

##### NumPy kutibxonasida esa quyidagicha ma'lumot turlari mavjud

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [3]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [275]:
arrint = np.random.randint(0, 10, size=(2,3))
arrint

array([[7, 4, 6],
       [9, 2, 6]])

In [4]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [6]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [5]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [8]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [9]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [10]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [18]:
arrint = np.random.randint(1,12, size=(3,4))
arrint

array([[ 7, 10,  3,  4],
       [ 5, 11, 10,  3],
       [ 5,  8, 11,  7]])

In [21]:
arrf1 = arrint.astype(float)
arrf2 = arrint.astype('S')
print(arrf1.dtype)
print(arrf1)
print('\n')
print(arrf2.dtype)
print(arrf2)

float64
[[ 7. 10.  3.  4.]
 [ 5. 11. 10.  3.]
 [ 5.  8. 11.  7.]]


|S11
[[b'7' b'10' b'3' b'4']
 [b'5' b'11' b'10' b'3']
 [b'5' b'8' b'11' b'7']]


### NumPy Array Copy vs View

In [25]:
sonlar = np.arange(1,13).reshape(3,4)
sonlar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
test = sonlar.copy()
test

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
test[:, -1] = 0
test

array([[ 1,  2,  3,  0],
       [ 5,  6,  7,  0],
       [ 9, 10, 11,  0]])

In [31]:
test1 = sonlar.view()
test1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
test1[:,-1]=111
test1

array([[  1,   2,   3, 111],
       [  5,   6,   7, 111],
       [  9,  10,  11, 111]])

### Numpy da arifmetik amallar va operatorlar 

### Numpy da massiv indexlari bilan ishlash

In [317]:
arr[3:6]

array([4, 5, 6])

In [315]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [318]:
massive = np.arange(1,25).reshape(4,6)
massive

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [337]:
massive[1:3, 3:5]

array([[10, 11],
       [16, 17]])

In [343]:
massive[:, -1] = 0
massive

array([[ 1,  2,  3,  4,  5,  0],
       [ 7,  8,  9, 10, 11,  0],
       [13, 14, 15, 16, 17,  0],
       [19, 20, 21, 22, 23,  0]])

In [347]:
massive[0,1]=222
massive

array([[  1, 222,   3,   4,   5,   0],
       [  7,   8,   9,  10,  11,   0],
       [ 13,  14,  15,  16,  17,   0],
       [ 19,  20,  21,  22,  23,   0]])

### Massiv o'lchamlari bilan ishlash
- reshape
- ndim
- resize

In [44]:
arr = np.arange(1, 25)
print(arr)
print(arr.size)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
24
int32
(24,)
1


In [45]:
newarr = arr.reshape(4,6)
print(arr)
print('\n')
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [46]:
print(newarr.size)
print(newarr)

24
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [47]:
newarr2 = newarr.reshape(3,8)
newarr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
newarr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6], ndmin=5)
arr

array([[[[[1, 2, 3, 4, 5, 6]]]]])

In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6]], ndmin=5)
arr

array([[[[[1, 2, 3],
          [4, 5, 6]]]]])

### Massiv elemetnlarini takroriyligi
- for ts
- nditer
- ndenumerate

In [70]:
massiv = np.arange(1,25)
massiv

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [72]:
my_massiv = massiv.reshape(6,4)
my_massiv

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [77]:
i = 1
for row in my_massiv:
    print(f'{i}-qator- {row}')
    i +=1

1-qator- [1 2 3 4]
2-qator- [5 6 7 8]
3-qator- [ 9 10 11 12]
4-qator- [13 14 15 16]
5-qator- [17 18 19 20]
6-qator- [21 22 23 24]


In [79]:
i = 0
for row in my_massiv:
    print(f'{i+1}-qator indeksi {i}- {row}')
    i +=1

1-qator indeksi 0- [1 2 3 4]
2-qator indeksi 1- [5 6 7 8]
3-qator indeksi 2- [ 9 10 11 12]
4-qator indeksi 3- [13 14 15 16]
5-qator indeksi 4- [17 18 19 20]
6-qator indeksi 5- [21 22 23 24]


In [93]:
print(my_massiv)
i = 0
for row in my_massiv:
    j=0
    for element in row:
        print(f'{i}:{j} elemnt {element}')
        j +=1
    i +=1

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
0:0 elemnt 1
0:1 elemnt 2
0:2 elemnt 3
0:3 elemnt 4
1:0 elemnt 5
1:1 elemnt 6
1:2 elemnt 7
1:3 elemnt 8
2:0 elemnt 9
2:1 elemnt 10
2:2 elemnt 11
2:3 elemnt 12
3:0 elemnt 13
3:1 elemnt 14
3:2 elemnt 15
3:3 elemnt 16
4:0 elemnt 17
4:1 elemnt 18
4:2 elemnt 19
4:3 elemnt 20
5:0 elemnt 21
5:1 elemnt 22
5:2 elemnt 23
5:3 elemnt 24


In [95]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)
print(np.nditer(arr))

1
2
3
4
5
6
7
8


In [100]:
for idx, x in np.ndenumerate(my_massiv):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12
(3, 0) 13
(3, 1) 14
(3, 2) 15
(3, 3) 16
(4, 0) 17
(4, 1) 18
(4, 2) 19
(4, 3) 20
(5, 0) 21
(5, 1) 22
(5, 2) 23
(5, 3) 24


### Massivlar ustida arifmetik amallar

In [116]:
matem = np.arange(1,13).reshape(4,3)
matem

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [120]:
print(matem>5)

[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]


In [119]:
print(matem<5)

[[ True  True  True]
 [ True False False]
 [False False False]
 [False False False]]


In [127]:
new_matem = matem[matem>4]
new_matem

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [128]:
print(new_matem.ndim)
print(new_matem.dtype)
print(new_matem.shape)
print(new_matem.size)

1
int32
(8,)
8


In [129]:
new_matem2 = new_matem.reshape(4,2)
new_matem2

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [133]:
birinchi = np.arange(1,9)
birinchi

array([1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
birinchi * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [136]:
birinchi / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [137]:
birinchi + 10

array([11, 12, 13, 14, 15, 16, 17, 18])

In [138]:
birinchi - 10

array([-9, -8, -7, -6, -5, -4, -3, -2])

In [139]:
birinchi ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [140]:
matem

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [141]:
matem * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [184]:
np.square(matem)

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [143]:
matem ** 1/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5],
       [5. , 5.5, 6. ]])

In [185]:
np.sqrt(matem)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [234]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


In [235]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [236]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [237]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [238]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


In [146]:
print(sum(birinchi))
print(birinchi)

36
[1 2 3 4 5 6 7 8]


In [164]:
print(matem)
# print('\n')
print(f'massiv elementlari barchasini yigindisi {np.sum(matem)}')
# print('\n')
print(f'massiv elementlari ustun yigindisi {np.sum(matem, axis=0)}')
# print('\n')
print(f'massiv elementlari qator yigindisi {np.sum(matem, axis=1)}')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
massiv elementlari barchasini yigindisi 78
massiv elementlari ustun yigindisi [22 26 30]
massiv elementlari qator yigindisi [ 6 15 24 33]


In [158]:
print(f'massiv elementlari barchasini yigindisi {np.sum(matem)}')

massiv elementlari yigindisi 78


In [159]:
print(f'massiv elementlari yigindisi {np.sum(matem, axis=0)}')

massiv elementlari yigindisi [22 26 30]


In [160]:
print(f'massiv elementlari yigindisi {np.sum(matem, axis=1)}')

massiv elementlari yigindisi [ 6 15 24 33]


In [165]:
birinchi

array([1, 2, 3, 4, 5, 6, 7, 8])

In [167]:
ikkinchi = np.arange(9, 17)
ikkinchi

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [168]:
print(birinchi + ikkinchi)

[10 12 14 16 18 20 22 24]


In [171]:
np.add(birinchi, ikkinchi)

array([10, 12, 14, 16, 18, 20, 22, 24])

In [173]:
print(birinchi - ikkinchi)

[-8 -8 -8 -8 -8 -8 -8 -8]


In [174]:
np.subtract(birinchi, ikkinchi)

array([-8, -8, -8, -8, -8, -8, -8, -8])

In [176]:
print(birinchi * ikkinchi)

[  9  20  33  48  65  84 105 128]


In [177]:
np.multiply(birinchi, ikkinchi)

array([  9,  20,  33,  48,  65,  84, 105, 128])

In [178]:
print(birinchi / ikkinchi)

[0.11111111 0.2        0.27272727 0.33333333 0.38461538 0.42857143
 0.46666667 0.5       ]


In [179]:
np.divide(birinchi, ikkinchi)

array([0.11111111, 0.2       , 0.27272727, 0.33333333, 0.38461538,
       0.42857143, 0.46666667, 0.5       ])

In [180]:
np.sqrt(birinchi)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712])

In [188]:
birinchi + matem

ValueError: operands could not be broadcast together with shapes (8,) (4,3) 

In [189]:
bir = np.arange(1,10).reshape(3,3)
bir

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [192]:
ikki = np.array([10,10,10])
uch = ikki.reshape(3,1)
uch

array([[10],
       [10],
       [10]])

In [191]:
bir+ikki

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [193]:
bir+uch

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [239]:
arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [240]:
arr = np.around(3.1666, 2)

print(arr)

3.17


### Massivlarni birlashtirish

In [214]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [215]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [218]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [216]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [219]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [220]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [221]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### Massivlarni ajratish

In [226]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [227]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [228]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [229]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [230]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [232]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr)
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [233]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Massiv elementini izlash

In [241]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [242]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [243]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [244]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [246]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [247]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [248]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Massivda Matematik va statistik funksiyalar

### Numpy da NUN qiymatlar bilan ishlash

In [101]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))
# Prints "[1, 1, 2, 3, 6, 8, 10]"

[1, 1, 2, 3, 6, 8, 10]


In [109]:
kimsiz = input('Talabamisiz talabaman/talaba emasman')
if kimsiz.lower() == 'talabaman' or kimsiz.lower()=='ha':
    print("Yaxshi o'qing talaba")
else:
    print("yaxshi o'qimagansiz")    

Talabamisiz talabaman/talaba emasman talabaman


Yaxshi o'qing talaba


In [113]:
kimsiz = int(input("Talabamisiz ha bo'lsa 1/aks xolda 0 ni kiriting"))
if kimsiz == 1:
    print("Yaxshi o'qing talaba")
else:
    print("yaxshi o'qimagansiz")    

Talabamisiz ha bo'lsa 1/aks xolda 0 ni kiriting 1


Yaxshi o'qing talaba
